name: JavaFX CI/CD with Security Scanning

on: [push, pull_request]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    continue-on-error: true  # Prevent workflow failure
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install

    - name: Security Scan
      id: security-scan
      run: |
        mvn dependency-check:check
        echo "result=success" >> $GITHUB_OUTPUT
      continue-on-error: true

    - name: Upload Security Report
      if: always() && steps.security-scan.outputs.result != 'success'
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          target/dependency-check-report.html
          dependency-check-data/*.json

    - name: Upload Application Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: video-player
        path: target/*.jar
