name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: path/to/your/pom  # Update this path to the actual directory containing your pom.xml
        run: mvn clean install
      - name: Run tests
        working-directory: path/to/your/pom  # Update this path to the actual directory containing your pom.xml
        run: mvn test
      - name: Code analysis
        working-directory: path/to/your/pom  # Update this path to the actual directory containing your pom.xml
        run: mvn verify
      - name: Dependency check
        working-directory: path/to/your/pom  # Update this path to the actual directory containing your pom.xml
        run: mvn dependency-check:check
