    name: CI Workflow

    on:
        push:
            branches: [main]
        pull_request:
            branches: [main]

    jobs:
        build:
            runs-on: ubuntu-latest

            steps:
                - uses: actions/checkout@v3
                - name: Set up JDK 17
                  uses: actions/setup-java@v3
                  with:
                    java-version: '17'
                    distribution: 'temurin'
                - name: Build with Maven
                  run: mvn clean install -f ./pom.xml
                - name: Run tests
                  run: mvn test
                - name: Code analysis
                  run:  mvn  verify
                - name: Dependency check
                  run: mvn dependency-check:check
